# Site settings
title: Life-Long Learner
email: georgios.i.kyritsis@gmail.com
description: "A Blog from a life-long learner."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 474f56 #80B3FF
  secondary: 00511a #FD6E8A
  secondary-dark: a1a1a1 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/inamoto21
  - title: linkedin
    url: https://www.linkedin.com/profile/view?id=263300260&trk=spm_pic
  - title: facebook
    url: https://www.facebook.com/gkyritsis21
  - title: google-plus
    url: https://plus.google.com/u/0/115387831445448806938/posts
  - title: instagram 
    url: http://instagram.com/inamoto21
  - title: github
    url: http://github.com/GeorgiosKyritsis

# Postal address (add as many lines as necessary)
address:
  - line: Leoforos Pentelis 23A
  - line: Vrilissia, 15235, Greece

# Build settings
markdown: kramdown
permalink: pretty
